name: Performance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # Runs every day at 5am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:
  prepare:
    name: Performance benchmark on ubuntu-22.04 with Node.js 22.x
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js 22.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'
      - name: Use Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'
      - name: Build
        shell: bash
        run: npm ci
      - name: Checkout Theia
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: eclipse-theia/theia
          path: ./theia
      - name: Copy webpack config
        shell: bash
        run: |
          cp -f ./configs/theia.production.webpack.config.js ./theia/examples/browser/webpack.config.js
          cp -f ./configs/theia.production.webpack.config.js ./theia/examples/electron/webpack.config.js
      - name: Build Theia
        shell: bash
        working-directory: ./theia
        run: |
          npm ci
          npm run compile
          npm run download:plugins -- --rate-limit 1
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      - name: Build Browser App (Production)
        shell: bash
        working-directory: ./theia/examples/browser
        run: |
          npm run build:production
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      - name: Build Electron App (Production)
        shell: bash
        working-directory: ./theia/examples/electron
        run: |
          npm run rebuild && npx theia build --mode production
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      - name: Cache Build Result
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: build-result
        with:
          path: ./*
          key: ${{ github.run_number }}

  run-browser-tests:
    name: Performance browser benchmark on ubuntu-22.04 with Node.js 22.x
    runs-on: ubuntu-22.04
    needs: [prepare]
    strategy:
      matrix:
        run: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    timeout-minutes: 40
    steps:
      - name: Restore Build Result (#${{ matrix.run }})
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: build-result
        with:
          path: ./*
          key: ${{ github.run_number }}
          fail-on-cache-miss: true
      - name: Use Node.js 22.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
      - name: Use Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"
      - name: Install Playwright Chromium
        shell: bash
        run: npx playwright install chromium
      - name: Get History
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: gh-pages
          path: gh-pages
      - name: Run Theia browser backend (#${{ matrix.run }})
        shell: bash
        working-directory: ./theia/examples/browser
        run: npm run start:debug &
      - name: Run Performance Measurement / browser (#${{ matrix.run }})
        shell: bash
        run: npm run performance
        env:
          RUN_NO: ${{ matrix.run }}
      - name: Upload performance measurement / browser (#${{ matrix.run }})
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: performance-measurement-browser-${{ github.run_number }}-${{ matrix.run }}
          path: performance-metrics/*

  run-electron-tests:
    name: Performance electron benchmark on ubuntu-22.04 with Node.js 22.x
    runs-on: ubuntu-22.04
    needs: [prepare]
    strategy:
      matrix:
        run: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    timeout-minutes: 40
    steps:
      - name: Restore Build Result (#${{ matrix.run }})
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: build-result
        with:
          path: ./*
          key: ${{ github.run_number }}
          fail-on-cache-miss: true
      - name: Use Node.js 22.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
      - name: Use Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"
      - name: Install Playwright Chromium
        shell: bash
        run: npx playwright install chromium
      - name: Get History
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: gh-pages
          path: gh-pages
      - name: Prepare Electron test config
        shell: bash
        run: |
          mkdir -p /tmp/theia-test-config
          echo '{ "security.workspace.trust.enabled": false }' > /tmp/theia-test-config/settings.json
      - name: Run Performance Measurement / electron (#${{ matrix.run }})
        shell: bash
        run: xvfb-run npm run performance-on-electron
        env:
          RUN_NO: ${{ matrix.run }}
          NODE_PATH: ./theia/node_modules
          THEIA_CONFIG_DIR: /tmp/theia-test-config
      - name: Upload performance measurement / electron (#${{ matrix.run }})
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: performance-measurement-electron-${{ github.run_number }}-${{ matrix.run }}
          path: performance-metrics/*

  generate-report:
    name: Create Performance Report
    runs-on: ubuntu-22.04
    needs: [run-browser-tests, run-electron-tests]
    steps:
      - name: Restore Build Result
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: build-result
        with:
          path: ./*
          key: ${{ github.run_number }}
          fail-on-cache-miss: true
      - name: Get History
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        if: always() && github.ref == 'refs/heads/main'
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Download Performance Measurements
        uses: actions/download-artifact@b14cf4c92620c250e1c074ab0a5800e37df86765 # v4.2.0
        with:
          pattern: performance-measurement-*-${{ github.run_number }}-*
          path: performance-metrics
          merge-multiple: true
      - name: Prepare Browser Report
        if: always() && github.ref == 'refs/heads/main'
        shell: bash
        run: npm run performance-report
      - name: Prepare Electron Report
        if: always() && github.ref == 'refs/heads/main'
        shell: bash
        run: npm run performance-report-electron
      - name: Publish Report
        if: always() && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
